meta_title: "Find your best candidates!"
meta_description: "WeRes is the first intelligent platform created to share candidates between recruiters."
meta_image: "grandlogo.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@weresrecruit" # indispensable pour les Twitter Cards
